#' plot.lconnect
#' @title Plot lconnect object
#' @description Plot lconnect object with clusters indicated by different colors.
#' Aditional arguments accepted by plot() or plot.sf() can be included.
#' @param x lconnect object generated by upload_land()
#' @param ... other options passed to plot().
#' @param key.pos TRUE/FALSE. If TRUE adds a key to the plot
#' @return Nothing. Side-effect: plots graphs.
#' @method plot lconnect
#' @S3method plot lconnect
plot.lconnect <- function(x, ..., key.pos){
  if(missing(key.pos)){
    key.pos <- NULL
  }
  land$landscape$clusters <- as.factor(land$landscape$clusters)
  graphics::plot(x$landscape, key.pos = key.pos, border = NA, reset = F, ...)
  graphics::plot(x$boundary, key.pos = key.pos, add = T, border = "grey", ...)
}