#' plot.lconnect
#' @title Plot lconnect object
#' @description Plot lconnect object with clusters indicated by different colors.
#' Aditional arguments accepted by plot() or plot.sf() can be included.
#' @param x lconnect object generated by upload_land()
#' @param ... other options passed to plot().
#' @return Nothing. Side-effect: plots graphs.
#' @method plot lconnect
#' @S3method plot lconnect
plot.lconnect <- function(x, ...){
  land$landscape$clusters <- as.factor(land$landscape$clusters)
  graphics::plot(x$landscape,  border = NA, reset = F, ...)
  graphics::plot(x$boundary,  add = T, border = "grey", ...)
}

