#' @title Plot pimp object
#' @description Method of the generic \code{\link[graphics]{plot}} for pimp
#' objects.
#' @param x pimp object generated by \code{\link{patch_imp}}
#' @param ... other options passed to \code{\link[graphics]{plot}} or 
#' \code{\link[sf]{plot.sf}}.
#' @param main string with plot title
#' @return Plot with patch importance
#' @method plot pimp
#' @S3method plot pimp
#' @author Bruno Silva
#' @author Frederico Mestre
#' @details Plot patch importance with percentage value per patch. This value
#' indicates the percentage of reduction in the connectivity metric that the 
#' loss of that patch represents in the landscape. Aditional arguments accepted
#' by \code{\link[graphics]{plot}} or \code{\link[sf]{plot.sf}} can be included.
plot.pimp <- function(x, ..., main){
  if(missing(main)){
    main <- "Importance (%)"
  }
  cols <- length(x$prioritization)
  graphics::plot(x$landscape["attributes"], border = NA,
                 main = main, ...)
}