#' @title Plot lconnect object
#' @description Method of the generic \code{\link[graphics]{plot}} for lconnect
#' objects.
#' @param x lconnect object generated by \code{\link{upload_land}}
#' @param ... other options passed to \code{\link[graphics]{plot}}.
#' @details Plot patches with different colours representing cluster identity.
#' Aditional arguments accepted by \code{\link[graphics]{plot}} or
#' \code{\link[sf]{plot.sf}} can be included.
#' @return Plot with clusters
#' @method plot lconnect
#' @S3method plot lconnect
#' @author Bruno Silva
#' @author Frederico Mestre
plot.lconnect <- function(x, ...){
  x$landscape$clusters <- as.factor(x$landscape$clusters)
  graphics::plot(x$landscape,  key.pos = NULL ,border = NA, reset = F, ...)
  graphics::plot(x$boundary,  add = T, border = "grey", ...)
}

