#' plot.pimp
#' @title Plot pimp object
#' @description Plot pimp object patch importance indicated by different colors.
#' Aditional arguments accepted by plot() or plot.sf() can be included.
#' @param x pimp object generated by patch_imp()
#' @param ... other options passed to plot().
#' @param main character with plot title
#' @return Nothing. Side-effect: plots graphs.
#' @method plot pimp
#' @S3method plot pimp
#' @author Bruno Silva
#' @author Frederico Mestre
plot.pimp <- function(x, ..., main){
  if(missing(main)){
    main <- "Importance (%)"
  }
  cols <- length(x$prioritization)
  graphics::plot(x$landscape["attributes"], border = NA,
                 main = main, ...)
}